"""
Logistic Regression with interaction terms for the context-switching task.

Run from project root:
    uv run python logistic_regression/fit.py
"""

from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    balanced_accuracy_score,
    confusion_matrix,
    log_loss,
    roc_auc_score,
)
from sklearn.preprocessing import PolynomialFeatures

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
SCRIPT_DIR = Path(__file__).parent
DATA_DIR = SCRIPT_DIR.parent / "data"
REPORT_PATH = SCRIPT_DIR / "REPORT.md"

FEATURES = [
    "previous_response",
    "previous_reward",
    "is_vis_target",
    "is_vis_non_target",
    "is_aud_target",
    "is_aud_non_target",
]
TARGET = "target_response"

# ---------------------------------------------------------------------------
# Load data
# ---------------------------------------------------------------------------
print("Loading training data ...")
train_df = pd.read_parquet(DATA_DIR / "training_set.parquet")
print(f"  Training set: {len(train_df):,} trials")

print("Loading test data ...")
test_df = pd.read_parquet(DATA_DIR / "test_set.parquet")
print(f"  Test set:     {len(test_df):,} trials")

X_train_raw = train_df[FEATURES].values.astype(float)
y_train = train_df[TARGET].values.astype(int)

X_test_raw = test_df[FEATURES].values.astype(float)
y_test = test_df[TARGET].values.astype(int)

# ---------------------------------------------------------------------------
# Interaction terms
# ---------------------------------------------------------------------------
print("Generating interaction features (degree=2, interaction_only=True) ...")
poly = PolynomialFeatures(degree=2, interaction_only=True, include_bias=False)
X_train = poly.fit_transform(X_train_raw)
X_test = poly.transform(X_test_raw)

feature_names = poly.get_feature_names_out(FEATURES)
print(f"  Total features (main + interactions): {len(feature_names)}")

# ---------------------------------------------------------------------------
# Fit model
# ---------------------------------------------------------------------------
print("Fitting logistic regression ...")
model = LogisticRegression(
    solver="lbfgs",
    max_iter=1000,
    random_state=0,
)
model.fit(X_train, y_train)
print("  Done.")

# ---------------------------------------------------------------------------
# Coefficients & odds ratios
# ---------------------------------------------------------------------------
intercept = model.intercept_[0]
coefficients = model.coef_[0]
odds_ratios = np.exp(coefficients)

coef_df = pd.DataFrame(
    {
        "feature": feature_names,
        "coefficient": coefficients,
        "odds_ratio": odds_ratios,
    }
).sort_values("coefficient", key=abs, ascending=False)

print("\nCoefficients (sorted by |coefficient|):")
for _, row in coef_df.iterrows():
    print(f"  {row['feature']:45s}  coef={row['coefficient']:+.4f}  OR={row['odds_ratio']:.4f}")
print(f"  {'(intercept)':45s}  coef={intercept:+.4f}")

# ---------------------------------------------------------------------------
# Predictions & metrics
# ---------------------------------------------------------------------------
print("\nEvaluating on test set ...")
y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:, 1]

acc = accuracy_score(y_test, y_pred)
bal_acc = balanced_accuracy_score(y_test, y_pred)
auc = roc_auc_score(y_test, y_prob)
ll = log_loss(y_test, y_prob)
cm = confusion_matrix(y_test, y_pred)

print(f"  Accuracy:          {acc:.4f}")
print(f"  Balanced accuracy: {bal_acc:.4f}")
print(f"  AUC-ROC:           {auc:.4f}")
print(f"  Log-loss:          {ll:.4f}")
print(f"  Confusion matrix:\n{cm}")

# ---------------------------------------------------------------------------
# Write REPORT.md
# ---------------------------------------------------------------------------
print(f"\nWriting report to {REPORT_PATH} ...")

tn, fp, fn, tp = cm.ravel()

lines: list[str] = []
w = lines.append

w("# Logistic Regression -- Results")
w("")
w("*Auto-generated by `logistic_regression/fit.py`.*")
w("")
w("## Data")
w("")
w(f"- Training trials: {len(train_df):,}")
w(f"- Test trials: {len(test_df):,}")
w(f"- Features (main): {len(FEATURES)}")
w(f"- Features (main + interactions): {len(feature_names)}")
w("")
w("## Test-set metrics")
w("")
w("| Metric | Value |")
w("|---|---|")
w(f"| Accuracy | {acc:.4f} |")
w(f"| Balanced accuracy | {bal_acc:.4f} |")
w(f"| AUC-ROC | {auc:.4f} |")
w(f"| Log-loss | {ll:.4f} |")
w("")
w("## Confusion matrix")
w("")
w("|  | Predicted Negative | Predicted Positive |")
w("|---|---|---|")
w(f"| **Actual Negative** | {tn:,} | {fp:,} |")
w(f"| **Actual Positive** | {fn:,} | {tp:,} |")
w("")
w("## Coefficients and odds ratios")
w("")
w("Sorted by absolute coefficient value (largest effect first).")
w("")
w("| Feature | Coefficient | Odds Ratio |")
w("|---|---|---|")
for _, row in coef_df.iterrows():
    w(f"| {row['feature']} | {row['coefficient']:+.4f} | {row['odds_ratio']:.4f} |")
w(f"| *(intercept)* | {intercept:+.4f} | -- |")
w("")

REPORT_PATH.write_text("\n".join(lines), encoding="utf-8")
print("Done.")
